# Build stage
FROM golang:1.21-alpine3.18 AS builder
WORKDIR /app
COPY . .
RUN go build -o dbinsertor cmd/dbinsertor/main.go

# Run stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/dbinsertor .
COPY app.env .
COPY start.sh .
COPY wait-for.sh .
COPY internal/db/migration ./internal/db/migration

EXPOSE 3000 3000
CMD [ "/app/dbinsertor" ]
ENTRYPOINT [ "/app/start.sh" ]